apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-tas-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-tas-1 
  name: rhtap-tas-1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap-tas-1 
